### ISSUE TITLE
MD5

### ISSUE THREAD

**Issue by mnafshin** [projekt-opal/common#2]
As calculating Md5 is a library function, in my opinion it is better to make it a static function. And I prefer not to have main function inside a library class. @adibaba

**Comment by adibaba** [comment]
@mnafshin you are absolutely right.

This class offers static methods to generate the URIs. It uses constants and namespaces which are already in use:
https://github.com/projekt-opal/common/blob/master/src/main/java/org/dice_research/opal/common/utilities/UriRewriter.java

Already testet the methods:
https://github.com/projekt-opal/common/blob/master/src/test/java/org/dice_research/opal/common/UriRewriterTest.java

Could you review the code and evaluate, if it's ready to use?

**Comment by adibaba** [comment]
static method provided
